name: Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  S3_REPO: s3:debian.mecha.build
  URL: http://localhost

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install cargo-deb
      run: cargo install cargo-deb

    - name: Build
      run: cargo build --release

    - name: Generate .deb package
      run: cargo deb --no-build

    - name: List output
      run: |
        echo "Listing output:"
        ls -l target/debian

    - name: Add file to file system and local repo
      run: |
        FILENAME=$(ls target/debian/*.deb)
        BASENAME=$(basename $FILENAME)
        curl -F file=@$FILENAME ${{ env.URL }}/api/files/$BASENAME
        curl -X POST ${{ env.URL }}/api/repos/mechanix-debian-repo/file/$BASENAME

    - name: Update local repo
      run: |
        curl -X PUT -H 'Content-Type: application/json' --data '{"Signing": {"Skip":true}}' ${{ env.URL }}/api/publish/:./apollo

    - name: Publish updated repo to s3
      run: |
        curl -X PUT -H 'Content-Type: application/json' --data '{
          "Sources": [{"Name": "mechanix-debian-repo"}],
          "Architectures": ["arm64", "amd64"],
          "Signing": {"Skip":true}
        }' ${{ env.URL }}/api/publish/${{ env.S3_REPO }}:/apollo
